"""Add roll, pitch, yaw columns to CarData

Revision ID: ca4c8fbc2e94
Revises: 
Create Date: 2024-07-14 16:26:44.826118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca4c8fbc2e94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roll', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('pitch', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('yaw', sa.Float(), nullable=False))
        batch_op.drop_column('rpm')
        batch_op.drop_column('speed')
        batch_op.drop_column('throttle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('throttle', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('speed', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('rpm', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('yaw')
        batch_op.drop_column('pitch')
        batch_op.drop_column('roll')

    # ### end Alembic commands ###
